### ISSUE TITLE
Conflict with the gem "factory_girl_rails"

### ISSUE THREAD

**Issue by JasonSi** [jpush/jpush-api-ruby-client#25]
I failed to run my rspec after adding this gem. Does it overwrite some default methods in rails? Or something else?
```
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'factory_girl_rails'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `blank?' for class `FactoryGirl::DefinitionProxy'
Did you mean?  blank?
Backtrace for gem load error is:
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:6:in `undef_method'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:6:in `block in <class:DefinitionProxy>'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:5:in `each'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:5:in `<class:DefinitionProxy>'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:2:in `<module:FactoryGirl>'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/definition_proxy.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl.rb:35:in `require'
/var/lib/gems/2.3.0/gems/factory_girl-4.7.0/lib/factory_girl.rb:35:in `<top (required)>'
/var/lib/gems/2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:1:in `require'
/var/lib/gems/2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails.rb:1:in `require'
/var/lib/gems/2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/home/jason/Project/Bourne/config/application.rb:7:in `<top (required)>'
/home/jason/Project/Bourne/config/environment.rb:2:in `require_relative'
/home/jason/Project/Bourne/config/environment.rb:2:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/jason/Project/Bourne/spec/rails_helper.rb:3:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/jason/Project/Bourne/spec/controllers/api/v1/base_controller_spec.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
/var/lib/gems/2.3.0/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'
/usr/local/bin/rspec:23:in `load'
/usr/local/bin/rspec:23:in `<main>'
Bundler Error Backtrace:
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from /var/lib/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
	from /home/jason/Project/Bourne/config/application.rb:7:in `<top (required)>'
	from /home/jason/Project/Bourne/config/environment.rb:2:in `require_relative'
	from /home/jason/Project/Bourne/config/environment.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jason/Project/Bourne/spec/rails_helper.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jason/Project/Bourne/spec/controllers/api/v1/base_controller_spec.rb:1:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /var/lib/gems/2.3.0/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'
	from /usr/local/bin/rspec:23:in `load'
	from /usr/local/bin/rspec:23:in `<main>'

```

**Comment by helperhaps** [comment]
@JasonSi Yep! I added the :blank? method from Rails with **Refinement**.But I remember to use the using express. It can't be that.  Can you help me to make it reappear to fix it?

**Comment by JasonSi** [comment]
How to show you the reappearance? You can try **Rails 5.0** & **factory_girl_rails** & **jpush**

**Comment by helperhaps** [comment]
I need a minimal demo. Can you describe your issue with a repo in your Github? So that I could clone it to run rspec to reappear it. Cause I don't think I can make my demo the same as yours.Is that OK? Or else I have to guess for a long time.

**Comment by JasonSi** [comment]
All right.  I'm doing this. 

——Jason

**Comment by JasonSi** [comment]
https://github.com/JasonSi/jpush-demo 
Readme.md writed by Chinese is the description...

**Comment by helperhaps** [comment]
Fine

**Comment by JasonSi** [comment]
Actually, not only Rsepc, but also whatever commands I want to run will failed ... 
Such as 
```bash
rails g scaffold 
```
 This gem caused factory_girl_rails  Gem Load Error

**Comment by helperhaps** [comment]
It woks well with rails4, So I will look into it for what is happenning on earth. It may take some time.

**Comment by helperhaps** [comment]
@JasonSi But you can put the JPush Gem on the last line of the Gemfile file to avoid this exception for now.

**Comment by JasonSi** [comment]
OK! Thanks

——Jason

**Comment by helperhaps** [comment]
Oh, just put it on the next line of factory_girl gem is fine. The exception is thrown by factory_girl.

**Comment by JasonSi** [comment]
lol  
I found it.  

——Jason

**Comment by JasonSi** [comment]
So I don't know whether I should close this issue... If you want, you can close it. Or till this bug fixed.

**Comment by helperhaps** [comment]
I have to give up refinement. I will remove it in the next version to work with factory_girl. Now just use it as i was said.

**Comment by JasonSi** [comment]
OK

——Jason
