### ISSUE TITLE
jpush + factory_girl cause error

### ISSUE THREAD

**Issue by zhen639** [jpush/jpush-api-ruby-client#34]
I am using **ruby-2.3.1** + **rails (5.0.1)** + **jpush (4.0.5)** + **factory_girl_rails (4.8.0)**.
The following error happened while I running rspec 

```
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'factory_girl_rails'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `blank?' for class `FactoryGirl::DefinitionProxy'
Did you mean?  blank?
Backtrace for gem load error is:
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:6:in `undef_method'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:6:in `block in <class:DefinitionProxy>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:5:in `each'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:5:in `<class:DefinitionProxy>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:2:in `<module:FactoryGirl>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl/definition_proxy.rb:1:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.8.0/lib/factory_girl.rb:35:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.8.0/lib/factory_girl_rails/railtie.rb:1:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/factory_girl_rails-4.8.0/lib/factory_girl_rails.rb:1:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/config/application.rb:7:in `<top (required)>'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/config/environment.rb:2:in `require_relative'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/config/environment.rb:2:in `<top (required)>'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/rails_helper.rb:3:in `require'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/rails_helper.rb:3:in `<top (required)>'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/models/ability_spec.rb:2:in `require'
/Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/models/ability_spec.rb:2:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
/Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
/Users/czliu/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `load'
/Users/czliu/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `<main>'
/Users/czliu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/czliu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/config/application.rb:7:in `<top (required)>'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/config/environment.rb:2:in `require_relative'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/config/environment.rb:2:in `<top (required)>'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/rails_helper.rb:3:in `require'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/rails_helper.rb:3:in `<top (required)>'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/models/ability_spec.rb:2:in `require'
	from /Users/czliu/Works/ConsenLabs/geth-relay-rails/spec/models/ability_spec.rb:2:in `<top (required)>'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `load'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `<main>'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/czliu/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

```

Everything is ok if I remove jpush gem...

Regards!

**Comment by zhen639** [comment]
Solved by following post so that will close this issue.
#31

**Comment by helperhaps** [comment]
是的，你暂时可以这么做，我这边在着手去掉 redfine 的语法，以及简化代码
